public class Song {
    //Implementing Song Class fields:
    private String title;
    private double duration;

    //Creating a main Constructor:
    public Song (String title, double duration) {
        this.title = title;
        this.duration = duration;
    }

    //Creating the getter for the title of the song:
    public String getTitle() {
        return this.title;
    }

    //Overriding toString method (which returns a string) in order for me to show the
    //the contents of a class in a string format and not a Song class format, like
    //Song@7f674d (automatically generated by Java) during a print calling;

    //Overriding this method also allows IntelliJ to print its contents without actually calling the method:
    @Override
    public String toString() {
        return this.title + ": " + this.duration;
    }


}
