public class GettersAndSetterQuicklyWay {
    private int testOne;
    private String testTwo;
    private boolean testThree;

    // A quickly (and sneaky) way to generate getter and setter for classes is:
    // On the main navigation bar click on CODE then select GENERATE then GETTERS and/or SETTERS;
    // Then you'll be prompt to select which variables you wanna create getters and/or setters,
    // select the variables you want then click OK; The result is the following:

    //this are the setters generated by intelliJ:
    public void setTestOne(int testOne) {
        this.testOne = testOne;
    }

    public void setTestTwo(String testTwo) {
        this.testTwo = testTwo;
    }

    public void setTestThree(boolean testThree) {
        this.testThree = testThree;
    }

    //this are the getters generated by intelliJ:
    public int getTestOne() {
        return testOne;
    }

    public String getTestTwo() {
        return testTwo;
    }

    public boolean isTestThree() {
        return testThree;
    }
}
